package com.nju.assigntask.entity;

import java.io.Serializable;

public class Myreceive implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.releaseid
     *
     * @mbg.generated
     */
    private Integer releaseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.dividedid
     *
     * @mbg.generated
     */
    private Integer dividedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.subtaskId_1
     *
     * @mbg.generated
     */
    private Integer subtaskid_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.subtaskId_2
     *
     * @mbg.generated
     */
    private Integer subtaskid_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.subtaskId_3
     *
     * @mbg.generated
     */
    private Integer subtaskid_3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.subtaskId_4
     *
     * @mbg.generated
     */
    private Integer subtaskid_4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.subtaskId_5
     *
     * @mbg.generated
     */
    private Integer subtaskid_5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.subtaskId_6
     *
     * @mbg.generated
     */
    private Integer subtaskid_6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.subtaskId_7
     *
     * @mbg.generated
     */
    private Integer subtaskid_7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.subtaskId_8
     *
     * @mbg.generated
     */
    private Integer subtaskid_8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.subtaskId_9
     *
     * @mbg.generated
     */
    private Integer subtaskid_9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.subtaskId_10
     *
     * @mbg.generated
     */
    private Integer subtaskid_10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myreceive.ifComplete
     *
     * @mbg.generated
     */
    private String ifcomplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myreceive
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.id
     *
     * @return the value of myreceive.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.id
     *
     * @param id the value for myreceive.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.userId
     *
     * @return the value of myreceive.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.userId
     *
     * @param userid the value for myreceive.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.releaseid
     *
     * @return the value of myreceive.releaseid
     *
     * @mbg.generated
     */
    public Integer getReleaseid() {
        return releaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.releaseid
     *
     * @param releaseid the value for myreceive.releaseid
     *
     * @mbg.generated
     */
    public void setReleaseid(Integer releaseid) {
        this.releaseid = releaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.dividedid
     *
     * @return the value of myreceive.dividedid
     *
     * @mbg.generated
     */
    public Integer getDividedid() {
        return dividedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.dividedid
     *
     * @param dividedid the value for myreceive.dividedid
     *
     * @mbg.generated
     */
    public void setDividedid(Integer dividedid) {
        this.dividedid = dividedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.subtaskId_1
     *
     * @return the value of myreceive.subtaskId_1
     *
     * @mbg.generated
     */
    public Integer getSubtaskid_1() {
        return subtaskid_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.subtaskId_1
     *
     * @param subtaskid_1 the value for myreceive.subtaskId_1
     *
     * @mbg.generated
     */
    public void setSubtaskid_1(Integer subtaskid_1) {
        this.subtaskid_1 = subtaskid_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.subtaskId_2
     *
     * @return the value of myreceive.subtaskId_2
     *
     * @mbg.generated
     */
    public Integer getSubtaskid_2() {
        return subtaskid_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.subtaskId_2
     *
     * @param subtaskid_2 the value for myreceive.subtaskId_2
     *
     * @mbg.generated
     */
    public void setSubtaskid_2(Integer subtaskid_2) {
        this.subtaskid_2 = subtaskid_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.subtaskId_3
     *
     * @return the value of myreceive.subtaskId_3
     *
     * @mbg.generated
     */
    public Integer getSubtaskid_3() {
        return subtaskid_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.subtaskId_3
     *
     * @param subtaskid_3 the value for myreceive.subtaskId_3
     *
     * @mbg.generated
     */
    public void setSubtaskid_3(Integer subtaskid_3) {
        this.subtaskid_3 = subtaskid_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.subtaskId_4
     *
     * @return the value of myreceive.subtaskId_4
     *
     * @mbg.generated
     */
    public Integer getSubtaskid_4() {
        return subtaskid_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.subtaskId_4
     *
     * @param subtaskid_4 the value for myreceive.subtaskId_4
     *
     * @mbg.generated
     */
    public void setSubtaskid_4(Integer subtaskid_4) {
        this.subtaskid_4 = subtaskid_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.subtaskId_5
     *
     * @return the value of myreceive.subtaskId_5
     *
     * @mbg.generated
     */
    public Integer getSubtaskid_5() {
        return subtaskid_5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.subtaskId_5
     *
     * @param subtaskid_5 the value for myreceive.subtaskId_5
     *
     * @mbg.generated
     */
    public void setSubtaskid_5(Integer subtaskid_5) {
        this.subtaskid_5 = subtaskid_5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.subtaskId_6
     *
     * @return the value of myreceive.subtaskId_6
     *
     * @mbg.generated
     */
    public Integer getSubtaskid_6() {
        return subtaskid_6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.subtaskId_6
     *
     * @param subtaskid_6 the value for myreceive.subtaskId_6
     *
     * @mbg.generated
     */
    public void setSubtaskid_6(Integer subtaskid_6) {
        this.subtaskid_6 = subtaskid_6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.subtaskId_7
     *
     * @return the value of myreceive.subtaskId_7
     *
     * @mbg.generated
     */
    public Integer getSubtaskid_7() {
        return subtaskid_7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.subtaskId_7
     *
     * @param subtaskid_7 the value for myreceive.subtaskId_7
     *
     * @mbg.generated
     */
    public void setSubtaskid_7(Integer subtaskid_7) {
        this.subtaskid_7 = subtaskid_7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.subtaskId_8
     *
     * @return the value of myreceive.subtaskId_8
     *
     * @mbg.generated
     */
    public Integer getSubtaskid_8() {
        return subtaskid_8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.subtaskId_8
     *
     * @param subtaskid_8 the value for myreceive.subtaskId_8
     *
     * @mbg.generated
     */
    public void setSubtaskid_8(Integer subtaskid_8) {
        this.subtaskid_8 = subtaskid_8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.subtaskId_9
     *
     * @return the value of myreceive.subtaskId_9
     *
     * @mbg.generated
     */
    public Integer getSubtaskid_9() {
        return subtaskid_9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.subtaskId_9
     *
     * @param subtaskid_9 the value for myreceive.subtaskId_9
     *
     * @mbg.generated
     */
    public void setSubtaskid_9(Integer subtaskid_9) {
        this.subtaskid_9 = subtaskid_9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.subtaskId_10
     *
     * @return the value of myreceive.subtaskId_10
     *
     * @mbg.generated
     */
    public Integer getSubtaskid_10() {
        return subtaskid_10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.subtaskId_10
     *
     * @param subtaskid_10 the value for myreceive.subtaskId_10
     *
     * @mbg.generated
     */
    public void setSubtaskid_10(Integer subtaskid_10) {
        this.subtaskid_10 = subtaskid_10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myreceive.ifComplete
     *
     * @return the value of myreceive.ifComplete
     *
     * @mbg.generated
     */
    public String getIfcomplete() {
        return ifcomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myreceive.ifComplete
     *
     * @param ifcomplete the value for myreceive.ifComplete
     *
     * @mbg.generated
     */
    public void setIfcomplete(String ifcomplete) {
        this.ifcomplete = ifcomplete == null ? null : ifcomplete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myreceive
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", releaseid=").append(releaseid);
        sb.append(", dividedid=").append(dividedid);
        sb.append(", subtaskid_1=").append(subtaskid_1);
        sb.append(", subtaskid_2=").append(subtaskid_2);
        sb.append(", subtaskid_3=").append(subtaskid_3);
        sb.append(", subtaskid_4=").append(subtaskid_4);
        sb.append(", subtaskid_5=").append(subtaskid_5);
        sb.append(", subtaskid_6=").append(subtaskid_6);
        sb.append(", subtaskid_7=").append(subtaskid_7);
        sb.append(", subtaskid_8=").append(subtaskid_8);
        sb.append(", subtaskid_9=").append(subtaskid_9);
        sb.append(", subtaskid_10=").append(subtaskid_10);
        sb.append(", ifcomplete=").append(ifcomplete);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}