package com.nju.assigntask.entity;

import java.io.Serializable;

public class Orderlist implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.dividedid
     *
     * @mbg.generated
     */
    private Integer dividedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.inputid
     *
     * @mbg.generated
     */
    private Integer inputid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.releaseid
     *
     * @mbg.generated
     */
    private Integer releaseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.itemname
     *
     * @mbg.generated
     */
    private String algname;
    private String itemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.score
     *
     * @mbg.generated
     */
    private double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.itemdes
     *
     * @mbg.generated
     */
    private String itemdes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.id
     *
     * @return the value of orderlist.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.id
     *
     * @param id the value for orderlist.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.dividedid
     *
     * @return the value of orderlist.dividedid
     *
     * @mbg.generated
     */
    public Integer getDividedid() {
        return dividedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.dividedid
     *
     * @param dividedid the value for orderlist.dividedid
     *
     * @mbg.generated
     */
    public void setDividedid(Integer dividedid) {
        this.dividedid = dividedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.inputid
     *
     * @return the value of orderlist.inputid
     *
     * @mbg.generated
     */
    public Integer getInputid() {
        return inputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.inputid
     *
     * @param inputid the value for orderlist.inputid
     *
     * @mbg.generated
     */
    public void setInputid(Integer inputid) {
        this.inputid = inputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.releaseid
     *
     * @return the value of orderlist.releaseid
     *
     * @mbg.generated
     */
    public Integer getReleaseid() {
        return releaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.releaseid
     *
     * @param releaseid the value for orderlist.releaseid
     *
     * @mbg.generated
     */
    public void setReleaseid(Integer releaseid) {
        this.releaseid = releaseid;
    }

    public String getAlgname() {
        return algname;
    }

    public void setAlgname(String algname) {
        this.algname = algname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.itemname
     *
     * @return the value of orderlist.itemname
     *
     * @mbg.generated
     */

    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.itemname
     *
     * @param itemname the value for orderlist.itemname
     *
     * @mbg.generated
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.score
     *
     * @return the value of orderlist.score
     *
     * @mbg.generated
     */
    public double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.score
     *
     * @param score the value for orderlist.score
     *
     * @mbg.generated
     */
    public void setScore(double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.itemdes
     *
     * @return the value of orderlist.itemdes
     *
     * @mbg.generated
     */
    public String getItemdes() {
        return itemdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.itemdes
     *
     * @param itemdes the value for orderlist.itemdes
     *
     * @mbg.generated
     */
    public void setItemdes(String itemdes) {
        this.itemdes = itemdes == null ? null : itemdes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dividedid=").append(dividedid);
        sb.append(", inputid=").append(inputid);
        sb.append(", releaseid=").append(releaseid);
        sb.append(", algname=").append(algname);
        sb.append(", itemname=").append(itemname);
        sb.append(", score=").append(score);
        sb.append(", itemdes=").append(itemdes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}