package com.nju.assigntask.entity;

import java.io.Serializable;

public class Recommend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.inputid
     *
     * @mbg.generated
     */
    private Integer inputid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.itemname
     *
     * @mbg.generated
     */
    private String itemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.itemdes
     *
     * @mbg.generated
     */
    private String itemdes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recommand
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.id
     *
     * @return the value of recommand.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.id
     *
     * @param id the value for recommand.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.inputid
     *
     * @return the value of recommand.inputid
     *
     * @mbg.generated
     */
    public Integer getInputid() {
        return inputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.inputid
     *
     * @param inputid the value for recommand.inputid
     *
     * @mbg.generated
     */
    public void setInputid(Integer inputid) {
        this.inputid = inputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.itemname
     *
     * @return the value of recommand.itemname
     *
     * @mbg.generated
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.itemname
     *
     * @param itemname the value for recommand.itemname
     *
     * @mbg.generated
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.itemdes
     *
     * @return the value of recommand.itemdes
     *
     * @mbg.generated
     */
    public String getItemdes() {
        return itemdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.itemdes
     *
     * @param itemdes the value for recommand.itemdes
     *
     * @mbg.generated
     */
    public void setItemdes(String itemdes) {
        this.itemdes = itemdes == null ? null : itemdes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommand
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", inputid=").append(inputid);
        sb.append(", itemname=").append(itemname);
        sb.append(", itemdes=").append(itemdes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}