package com.nju.assigntask.dao;

import com.nju.assigntask.entity.Algresult;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface AlgresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algresult
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algresult
     *
     * @mbg.generated
     */
    int insert(Algresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algresult
     *
     * @mbg.generated
     */
    Algresult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algresult
     *
     * @mbg.generated
     */
    List<Algresult> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algresult
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Algresult record);


    /**
     * 更新algresult表的score
     * @param id
     * @param score1
     */
    void updateScore1(int id,double score1);
    void updateScore2(int id,double score2);
 //   void updateScore(Algresult algresult);

    /**
     * 更新winalgname字段
     * @param algresult
     */
    void updateWinAlg(Algresult algresult);

    /**
     * 更新iffinal字段
     * @param algresult
     */
    void updateIffinal(Algresult algresult);

    /**
     * 插入记录
     * @param algresult
     */
    void insertRecord(Algresult algresult);

    /**
     *插入ahp记录
     * @param releaseid
     * @param algname
     */
    void insertRecordAhp(int releaseid,String algname,String iffinal);

    /**
     * 获取上一轮优胜算法名
     * @return
     */
    List<Algresult> selectNullWinAlgs();

    /**
     * 获取iffinal字段为空的算法名
     * @param releaseid
     * @return
     */
    List<String> selectNoFinalAlg(int releaseid);

    /**
     * 获取iffinal字段为空的记录id
     * @param releaseid
     * @return
     */
    List<Integer> selectNoFinalIds(int releaseid);
}