package com.nju.assigntask.dao;

import com.nju.assigntask.entity.Inputs;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface InputsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputs
     *
     * @mbg.generated
     */
    int insert(Inputs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputs
     *
     * @mbg.generated
     */
    List<Inputs> selectAll();

    /**
     * 查询该检索表所有内容
     * @param tablename
     * @return
     */
    List<Inputs> selectAllInput(@Param("tablename") String tablename);

    /**
     * 查询某检索表的某次检索
     * @param tablename
     * @param inputid
     * @return
     */
    Inputs selectByInputid(@Param("tablename") String tablename,@Param("inputid") int inputid);

}