package com.nju.assigntask.dao;

import com.nju.assigntask.entity.Recommend;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface RecommandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommand
     *
     * @mbg.generated
     */
    int insert(Recommend record);

    /**
     * 查找某个算法对应的所有推荐结果
     * @param tablename
     * @return
     */
    List<Recommend> selectAll(@Param("tablename") String tablename);

    /**
     * 查找算法对应的inputID的推荐结果
     * @param tablename
     * @param inputid
     * @return
     */
    List<Recommend> selectByInputid (@Param("tablename") String tablename,@Param("inputid") int inputid);

}