package com.nju.assigntask.dao;

import com.nju.assigntask.entity.User;
import com.nju.assigntask.entity.Userreceive;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface UserreceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbg.generated
     */
    int insert(Userreceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbg.generated
     */
    List<Userreceive> selectAll();

    User findUserByUserName(String username);

    /**
     * 根据用户查询
     * @param userId
     * @return
     */
    List<Userreceive> findByUserId(int userId);

    /**
     * 根据subtaskid查询score1和score2
     * @param subtaskid
     * @return
     */
    List<Double> selectScore1BySubtaskId(int subtaskid);
    List<Double> selectScore2BySubtaskId(int subtaskid);


    int selectAveScore1(Userreceive userreceive);
    int selectAveScore2(Userreceive userreceive);
    List<Integer> selectReleaseIdByUser(int userid);

    /**
     * 插入用户与任务之间的关系
     * @param userid
     * @param subtaskid
     * @param dividedid
     * @return
     */
    int insertSubTask(int userid,int subtaskid,int dividedid);
//    int insertSubTask(Userreceive userreceive);

    /**
     * 更新score
     * @param userreceive
     */
    void updateScore(Userreceive userreceive);

}