package com.nju.assigntask.dao;

import com.nju.assigntask.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * 通过用户名查询
     * @param username
     * @return
     */
    User findUserByUserName(String username);

    /**
     * 通过用户id查询
     * @param userid
     * @return
     */
    User findUserById(int userid);

    List<User> selectAllByTasking();

    /**
     * 通过tasking查询
     * @return
     */
    List selectAllIdByTasking();

    /**
     * 更新tasking字段
     * @param userId
     * @param tasking
     * @return
     */
    int updateTaking (int userId,int tasking);

    /**
     * 更新密码
     * @param userId
     * @param password
     * @return
     */
    int updatePassword(int userId, String password);
    /**
     * 通过邮箱查询
     * @param email
     * @return
     */
    User findUserByEmail(String email);
}