package com.nju.assigntask.dao;

import com.nju.assigntask.entity.Userrelease;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface UserreleaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelease
     *
     * @mbg.generated
     */
    int insert(Userrelease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelease
     *
     * @mbg.generated
     */
    List<Userrelease> selectAll();

    List<Integer> selectByUser(int userid);
}