package com.wx.assigntask.entity;

import java.io.Serializable;

public class Divided implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.dividedId
     *
     * @mbg.generated
     */
    private Integer dividedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.releaseId
     *
     * @mbg.generated
     */
    private Integer releaseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.inputid
     *
     * @mbg.generated
     */
    private int inputid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.algName1
     *
     * @mbg.generated
     */
    private String algname1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.algName2
     *
     * @mbg.generated
     */
    private String algname2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.ifDivided
     *
     * @mbg.generated
     */
    private String ifdivided;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.score1
     *
     * @mbg.generated
     */
    private float score1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.score2
     *
     * @mbg.generated
     */
    private float score2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.ifLatest
     *
     * @mbg.generated
     */
    private String iflatest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.winAlgname
     *
     * @mbg.generated
     */
    private String winalgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column divided.ifFinal
     *
     * @mbg.generated
     */
    private String iffinal;
    private String ordered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table divided
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.dividedId
     *
     * @return the value of divided.dividedId
     *
     * @mbg.generated
     */
    public Integer getDividedid() {
        return dividedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column divided.dividedId
     *
     * @param dividedid the value for divided.dividedId
     *
     * @mbg.generated
     */
    public void setDividedid(Integer dividedid) {
        this.dividedid = dividedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.releaseId
     *
     * @return the value of divided.releaseId
     *
     * @mbg.generated
     */
    public Integer getReleaseid() {
        return releaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column divided.releaseId
     *
     * @param releaseid the value for divided.releaseId
     *
     * @mbg.generated
     */
    public void setReleaseid(Integer releaseid) {
        this.releaseid = releaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.inputid
     *
     * @return the value of divided.inputid
     *
     * @mbg.generated
     */
    public int getInputid() {
        return inputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column divided.inputName
     *
     * @param inputid the value for divided.inputName
     *
     * @mbg.generated
     */
    public void setInputid(int inputid) {
        this.inputid = inputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.algName1
     *
     * @return the value of divided.algName1
     *
     * @mbg.generated
     */
    public String getAlgname1() {
        return algname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column divided.algName1
     *
     * @param algname1 the value for divided.algName1
     *
     * @mbg.generated
     */
    public void setAlgname1(String algname1) {
        this.algname1 = algname1 == null ? null : algname1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.algName2
     *
     * @return the value of divided.algName2
     *
     * @mbg.generated
     */
    public String getAlgname2() {
        return algname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column divided.algName2
     *
     * @param algname2 the value for divided.algName2
     *
     * @mbg.generated
     */
    public void setAlgname2(String algname2) {
        this.algname2 = algname2 == null ? null : algname2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.ifDivided
     *
     * @return the value of divided.ifDivided
     *
     * @mbg.generated
     */
    public String getIfdivided() {
        return ifdivided;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column divided.ifDivided
     *
     * @param ifdivided the value for divided.ifDivided
     *
     * @mbg.generated
     */
    public void setIfdivided(String ifdivided) {
        this.ifdivided = ifdivided == null ? null : ifdivided.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.score1
     *
     * @return the value of divided.score1
     *
     * @mbg.generated
     */
    public float getScore1() {
        return score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column divided.score1
     *
     * @param score1 the value for divided.score1
     *
     * @mbg.generated
     */

    public void setScore1(float score1) {
        this.score1 = score1;
    }

    public void setScore2(float score2) {
        this.score2 = score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.score2
     *
     * @return the value of divided.score2
     *
     * @mbg.generated
     */
    public float getScore2() {
        return score2;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.ifLatest
     *
     * @return the value of divided.ifLatest
     *
     * @mbg.generated
     */
    public String getIflatest() {
        return iflatest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column divided.ifLatest
     *
     * @param iflatest the value for divided.ifLatest
     *
     * @mbg.generated
     */
    public void setIflatest(String iflatest) {
        this.iflatest = iflatest == null ? null : iflatest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.winAlgname
     *
     * @return the value of divided.winAlgname
     *
     * @mbg.generated
     */
    public String getWinalgname() {
        return winalgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column divided.winAlgname
     *
     * @param winalgname the value for divided.winAlgname
     *
     * @mbg.generated
     */
    public void setWinalgname(String winalgname) {
        this.winalgname = winalgname == null ? null : winalgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column divided.ifFinal
     *
     * @return the value of divided.ifFinal
     *
     * @mbg.generated
     */
    public String getIffinal() {
        return iffinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column divided.ifFinal
     *
     * @param iffinal the value for divided.ifFinal
     *
     * @mbg.generated
     */
    public void setIffinal(String iffinal) {
        this.iffinal = iffinal == null ? null : iffinal.trim();
    }

    public String getOrdered() {
        return ordered;
    }

    public void setOrdered(String ordered) {
        this.ordered = ordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table divided
     *
     * @mbg.generated
     */


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dividedid=").append(dividedid);
        sb.append(", releaseid=").append(releaseid);
        sb.append(", inputid=").append(inputid);
        sb.append(", algname1=").append(algname1);
        sb.append(", algname2=").append(algname2);
        sb.append(", ifdivided=").append(ifdivided);
        sb.append(", score1=").append(score1);
        sb.append(", score2=").append(score2);
        sb.append(", iflatest=").append(iflatest);
        sb.append(", winalgname=").append(winalgname);
        sb.append(", iffinal=").append(iffinal);
        sb.append(", ordered=").append(ordered);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}