package com.wx.assigntask.entity;

import java.io.Serializable;

public class Inputs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inputs.inputid
     *
     * @mbg.generated
     */
    private Integer inputid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inputs.inputname
     *
     * @mbg.generated
     */
    private String inputname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inputs.inputdes
     *
     * @mbg.generated
     */
    private String inputdes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inputs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inputs.inputid
     *
     * @return the value of inputs.inputid
     *
     * @mbg.generated
     */
    public Integer getInputid() {
        return inputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inputs.inputid
     *
     * @param inputid the value for inputs.inputid
     *
     * @mbg.generated
     */
    public void setInputid(Integer inputid) {
        this.inputid = inputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inputs.inputname
     *
     * @return the value of inputs.inputname
     *
     * @mbg.generated
     */
    public String getInputname() {
        return inputname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inputs.inputname
     *
     * @param inputname the value for inputs.inputname
     *
     * @mbg.generated
     */
    public void setInputname(String inputname) {
        this.inputname = inputname == null ? null : inputname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inputs.inputdes
     *
     * @return the value of inputs.inputdes
     *
     * @mbg.generated
     */
    public String getInputdes() {
        return inputdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inputs.inputdes
     *
     * @param inputdes the value for inputs.inputdes
     *
     * @mbg.generated
     */
    public void setInputdes(String inputdes) {
        this.inputdes = inputdes == null ? null : inputdes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inputid=").append(inputid);
        sb.append(", inputname=").append(inputname);
        sb.append(", inputdes=").append(inputdes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}