package com.wx.assigntask.entity;

import java.io.Serializable;

public class Recommand implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.releaseid
     *
     * @mbg.generated
     */
    private Integer releaseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.inputname
     *
     * @mbg.generated
     */
    private String inputname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.name1
     *
     * @mbg.generated
     */
    private String name1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.name2
     *
     * @mbg.generated
     */
    private String name2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.name3
     *
     * @mbg.generated
     */
    private String name3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.name4
     *
     * @mbg.generated
     */
    private String name4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.name5
     *
     * @mbg.generated
     */
    private String name5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.name6
     *
     * @mbg.generated
     */
    private String name6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.name7
     *
     * @mbg.generated
     */
    private String name7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.name8
     *
     * @mbg.generated
     */
    private String name8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.name9
     *
     * @mbg.generated
     */
    private String name9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.name10
     *
     * @mbg.generated
     */
    private String name10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.inputdes
     *
     * @mbg.generated
     */
    private String inputdes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.des1
     *
     * @mbg.generated
     */
    private String des1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.des2
     *
     * @mbg.generated
     */
    private String des2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.des3
     *
     * @mbg.generated
     */
    private String des3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.des4
     *
     * @mbg.generated
     */
    private String des4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.des5
     *
     * @mbg.generated
     */
    private String des5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.des6
     *
     * @mbg.generated
     */
    private String des6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.des7
     *
     * @mbg.generated
     */
    private String des7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.des8
     *
     * @mbg.generated
     */
    private String des8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.des9
     *
     * @mbg.generated
     */
    private String des9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommand.des10
     *
     * @mbg.generated
     */
    private String des10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recommand
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.id
     *
     * @return the value of recommand.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.id
     *
     * @param id the value for recommand.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.releaseid
     *
     * @return the value of recommand.releaseid
     *
     * @mbg.generated
     */
    public Integer getReleaseid() {
        return releaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.releaseid
     *
     * @param releaseid the value for recommand.releaseid
     *
     * @mbg.generated
     */
    public void setReleaseid(Integer releaseid) {
        this.releaseid = releaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.inputname
     *
     * @return the value of recommand.inputname
     *
     * @mbg.generated
     */
    public String getInputname() {
        return inputname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.inputname
     *
     * @param inputname the value for recommand.inputname
     *
     * @mbg.generated
     */
    public void setInputname(String inputname) {
        this.inputname = inputname == null ? null : inputname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.name1
     *
     * @return the value of recommand.name1
     *
     * @mbg.generated
     */
    public String getName1() {
        return name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.name1
     *
     * @param name1 the value for recommand.name1
     *
     * @mbg.generated
     */
    public void setName1(String name1) {
        this.name1 = name1 == null ? null : name1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.name2
     *
     * @return the value of recommand.name2
     *
     * @mbg.generated
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.name2
     *
     * @param name2 the value for recommand.name2
     *
     * @mbg.generated
     */
    public void setName2(String name2) {
        this.name2 = name2 == null ? null : name2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.name3
     *
     * @return the value of recommand.name3
     *
     * @mbg.generated
     */
    public String getName3() {
        return name3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.name3
     *
     * @param name3 the value for recommand.name3
     *
     * @mbg.generated
     */
    public void setName3(String name3) {
        this.name3 = name3 == null ? null : name3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.name4
     *
     * @return the value of recommand.name4
     *
     * @mbg.generated
     */
    public String getName4() {
        return name4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.name4
     *
     * @param name4 the value for recommand.name4
     *
     * @mbg.generated
     */
    public void setName4(String name4) {
        this.name4 = name4 == null ? null : name4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.name5
     *
     * @return the value of recommand.name5
     *
     * @mbg.generated
     */
    public String getName5() {
        return name5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.name5
     *
     * @param name5 the value for recommand.name5
     *
     * @mbg.generated
     */
    public void setName5(String name5) {
        this.name5 = name5 == null ? null : name5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.name6
     *
     * @return the value of recommand.name6
     *
     * @mbg.generated
     */
    public String getName6() {
        return name6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.name6
     *
     * @param name6 the value for recommand.name6
     *
     * @mbg.generated
     */
    public void setName6(String name6) {
        this.name6 = name6 == null ? null : name6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.name7
     *
     * @return the value of recommand.name7
     *
     * @mbg.generated
     */
    public String getName7() {
        return name7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.name7
     *
     * @param name7 the value for recommand.name7
     *
     * @mbg.generated
     */
    public void setName7(String name7) {
        this.name7 = name7 == null ? null : name7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.name8
     *
     * @return the value of recommand.name8
     *
     * @mbg.generated
     */
    public String getName8() {
        return name8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.name8
     *
     * @param name8 the value for recommand.name8
     *
     * @mbg.generated
     */
    public void setName8(String name8) {
        this.name8 = name8 == null ? null : name8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.name9
     *
     * @return the value of recommand.name9
     *
     * @mbg.generated
     */
    public String getName9() {
        return name9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.name9
     *
     * @param name9 the value for recommand.name9
     *
     * @mbg.generated
     */
    public void setName9(String name9) {
        this.name9 = name9 == null ? null : name9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.name10
     *
     * @return the value of recommand.name10
     *
     * @mbg.generated
     */
    public String getName10() {
        return name10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.name10
     *
     * @param name10 the value for recommand.name10
     *
     * @mbg.generated
     */
    public void setName10(String name10) {
        this.name10 = name10 == null ? null : name10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.inputdes
     *
     * @return the value of recommand.inputdes
     *
     * @mbg.generated
     */
    public String getInputdes() {
        return inputdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.inputdes
     *
     * @param inputdes the value for recommand.inputdes
     *
     * @mbg.generated
     */
    public void setInputdes(String inputdes) {
        this.inputdes = inputdes == null ? null : inputdes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.des1
     *
     * @return the value of recommand.des1
     *
     * @mbg.generated
     */
    public String getDes1() {
        return des1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.des1
     *
     * @param des1 the value for recommand.des1
     *
     * @mbg.generated
     */
    public void setDes1(String des1) {
        this.des1 = des1 == null ? null : des1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.des2
     *
     * @return the value of recommand.des2
     *
     * @mbg.generated
     */
    public String getDes2() {
        return des2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.des2
     *
     * @param des2 the value for recommand.des2
     *
     * @mbg.generated
     */
    public void setDes2(String des2) {
        this.des2 = des2 == null ? null : des2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.des3
     *
     * @return the value of recommand.des3
     *
     * @mbg.generated
     */
    public String getDes3() {
        return des3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.des3
     *
     * @param des3 the value for recommand.des3
     *
     * @mbg.generated
     */
    public void setDes3(String des3) {
        this.des3 = des3 == null ? null : des3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.des4
     *
     * @return the value of recommand.des4
     *
     * @mbg.generated
     */
    public String getDes4() {
        return des4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.des4
     *
     * @param des4 the value for recommand.des4
     *
     * @mbg.generated
     */
    public void setDes4(String des4) {
        this.des4 = des4 == null ? null : des4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.des5
     *
     * @return the value of recommand.des5
     *
     * @mbg.generated
     */
    public String getDes5() {
        return des5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.des5
     *
     * @param des5 the value for recommand.des5
     *
     * @mbg.generated
     */
    public void setDes5(String des5) {
        this.des5 = des5 == null ? null : des5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.des6
     *
     * @return the value of recommand.des6
     *
     * @mbg.generated
     */
    public String getDes6() {
        return des6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.des6
     *
     * @param des6 the value for recommand.des6
     *
     * @mbg.generated
     */
    public void setDes6(String des6) {
        this.des6 = des6 == null ? null : des6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.des7
     *
     * @return the value of recommand.des7
     *
     * @mbg.generated
     */
    public String getDes7() {
        return des7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.des7
     *
     * @param des7 the value for recommand.des7
     *
     * @mbg.generated
     */
    public void setDes7(String des7) {
        this.des7 = des7 == null ? null : des7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.des8
     *
     * @return the value of recommand.des8
     *
     * @mbg.generated
     */
    public String getDes8() {
        return des8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.des8
     *
     * @param des8 the value for recommand.des8
     *
     * @mbg.generated
     */
    public void setDes8(String des8) {
        this.des8 = des8 == null ? null : des8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.des9
     *
     * @return the value of recommand.des9
     *
     * @mbg.generated
     */
    public String getDes9() {
        return des9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.des9
     *
     * @param des9 the value for recommand.des9
     *
     * @mbg.generated
     */
    public void setDes9(String des9) {
        this.des9 = des9 == null ? null : des9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommand.des10
     *
     * @return the value of recommand.des10
     *
     * @mbg.generated
     */
    public String getDes10() {
        return des10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommand.des10
     *
     * @param des10 the value for recommand.des10
     *
     * @mbg.generated
     */
    public void setDes10(String des10) {
        this.des10 = des10 == null ? null : des10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommand
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", releaseid=").append(releaseid);
        sb.append(", inputname=").append(inputname);
        sb.append(", name1=").append(name1);
        sb.append(", name2=").append(name2);
        sb.append(", name3=").append(name3);
        sb.append(", name4=").append(name4);
        sb.append(", name5=").append(name5);
        sb.append(", name6=").append(name6);
        sb.append(", name7=").append(name7);
        sb.append(", name8=").append(name8);
        sb.append(", name9=").append(name9);
        sb.append(", name10=").append(name10);
        sb.append(", inputdes=").append(inputdes);
        sb.append(", des1=").append(des1);
        sb.append(", des2=").append(des2);
        sb.append(", des3=").append(des3);
        sb.append(", des4=").append(des4);
        sb.append(", des5=").append(des5);
        sb.append(", des6=").append(des6);
        sb.append(", des7=").append(des7);
        sb.append(", des8=").append(des8);
        sb.append(", des9=").append(des9);
        sb.append(", des10=").append(des10);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}