package com.wx.assigntask.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Recommanddes implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.inputName
     *
     * @mbg.generated
     */
    private String inputname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.inputDes
     *
     * @mbg.generated
     */
    private String inputdes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.lstm1
     *
     * @mbg.generated
     */
    private String lstm1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.lstm2
     *
     * @mbg.generated
     */
    private String lstm2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.lstm3
     *
     * @mbg.generated
     */
    private String lstm3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.lstm4
     *
     * @mbg.generated
     */
    private String lstm4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.lstm5
     *
     * @mbg.generated
     */
    private String lstm5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.lstm6
     *
     * @mbg.generated
     */
    private String lstm6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.lstm7
     *
     * @mbg.generated
     */
    private String lstm7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.lstm8
     *
     * @mbg.generated
     */
    private String lstm8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.lstm9
     *
     * @mbg.generated
     */
    private String lstm9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.lstm10
     *
     * @mbg.generated
     */
    private String lstm10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.nn1
     *
     * @mbg.generated
     */
    private String nn1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.nn2
     *
     * @mbg.generated
     */
    private String nn2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.nn3
     *
     * @mbg.generated
     */
    private String nn3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.nn4
     *
     * @mbg.generated
     */
    private String nn4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.nn5
     *
     * @mbg.generated
     */
    private String nn5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.nn6
     *
     * @mbg.generated
     */
    private String nn6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.nn7
     *
     * @mbg.generated
     */
    private String nn7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.nn8
     *
     * @mbg.generated
     */
    private String nn8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.nn9
     *
     * @mbg.generated
     */
    private String nn9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.nn10
     *
     * @mbg.generated
     */
    private String nn10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.cnn1
     *
     * @mbg.generated
     */
    private String cnn1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.cnn2
     *
     * @mbg.generated
     */
    private String cnn2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.cnn3
     *
     * @mbg.generated
     */
    private String cnn3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.cnn4
     *
     * @mbg.generated
     */
    private String cnn4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.cnn5
     *
     * @mbg.generated
     */
    private String cnn5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.cnn6
     *
     * @mbg.generated
     */
    private String cnn6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.cnn7
     *
     * @mbg.generated
     */
    private String cnn7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.cnn8
     *
     * @mbg.generated
     */
    private String cnn8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.cnn9
     *
     * @mbg.generated
     */
    private String cnn9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.cnn10
     *
     * @mbg.generated
     */
    private String cnn10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.tfidf1
     *
     * @mbg.generated
     */
    private String tfidf1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.tfidf2
     *
     * @mbg.generated
     */
    private String tfidf2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.tfidf3
     *
     * @mbg.generated
     */
    private String tfidf3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.tfidf4
     *
     * @mbg.generated
     */
    private String tfidf4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.tfidf5
     *
     * @mbg.generated
     */
    private String tfidf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.tfidf6
     *
     * @mbg.generated
     */
    private String tfidf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.tfidf7
     *
     * @mbg.generated
     */
    private String tfidf7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.tfidf8
     *
     * @mbg.generated
     */
    private String tfidf8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.tfidf9
     *
     * @mbg.generated
     */
    private String tfidf9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.tfidf10
     *
     * @mbg.generated
     */
    private String tfidf10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.doc1
     *
     * @mbg.generated
     */
    private String doc1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.doc2
     *
     * @mbg.generated
     */
    private String doc2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.doc3
     *
     * @mbg.generated
     */
    private String doc3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.doc4
     *
     * @mbg.generated
     */
    private String doc4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.doc5
     *
     * @mbg.generated
     */
    private String doc5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.doc6
     *
     * @mbg.generated
     */
    private String doc6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.doc7
     *
     * @mbg.generated
     */
    private String doc7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.doc8
     *
     * @mbg.generated
     */
    private String doc8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.doc9
     *
     * @mbg.generated
     */
    private String doc9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.doc10
     *
     * @mbg.generated
     */
    private String doc10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.index1
     *
     * @mbg.generated
     */
    private String index1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.index2
     *
     * @mbg.generated
     */
    private String index2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.index3
     *
     * @mbg.generated
     */
    private String index3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.index4
     *
     * @mbg.generated
     */
    private String index4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.index5
     *
     * @mbg.generated
     */
    private String index5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.index6
     *
     * @mbg.generated
     */
    private String index6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.index7
     *
     * @mbg.generated
     */
    private String index7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.index8
     *
     * @mbg.generated
     */
    private String index8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.index9
     *
     * @mbg.generated
     */
    private String index9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommanddes.index10
     *
     * @mbg.generated
     */
    private String index10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recommanddes
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.inputName
     *
     * @return the value of recommanddes.inputName
     *
     * @mbg.generated
     */
    public String getInputname() {
        return inputname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.inputName
     *
     * @param inputname the value for recommanddes.inputName
     *
     * @mbg.generated
     */
    public void setInputname(String inputname) {
        this.inputname = inputname == null ? null : inputname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.inputDes
     *
     * @return the value of recommanddes.inputDes
     *
     * @mbg.generated
     */
    public String getInputdes() {
        return inputdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.inputDes
     *
     * @param inputdes the value for recommanddes.inputDes
     *
     * @mbg.generated
     */
    public void setInputdes(String inputdes) {
        this.inputdes = inputdes == null ? null : inputdes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.lstm1
     *
     * @return the value of recommanddes.lstm1
     *
     * @mbg.generated
     */
    public String getLstm1() {
        return lstm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.lstm1
     *
     * @param lstm1 the value for recommanddes.lstm1
     *
     * @mbg.generated
     */
    public void setLstm1(String lstm1) {
        this.lstm1 = lstm1 == null ? null : lstm1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.lstm2
     *
     * @return the value of recommanddes.lstm2
     *
     * @mbg.generated
     */
    public String getLstm2() {
        return lstm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.lstm2
     *
     * @param lstm2 the value for recommanddes.lstm2
     *
     * @mbg.generated
     */
    public void setLstm2(String lstm2) {
        this.lstm2 = lstm2 == null ? null : lstm2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.lstm3
     *
     * @return the value of recommanddes.lstm3
     *
     * @mbg.generated
     */
    public String getLstm3() {
        return lstm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.lstm3
     *
     * @param lstm3 the value for recommanddes.lstm3
     *
     * @mbg.generated
     */
    public void setLstm3(String lstm3) {
        this.lstm3 = lstm3 == null ? null : lstm3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.lstm4
     *
     * @return the value of recommanddes.lstm4
     *
     * @mbg.generated
     */
    public String getLstm4() {
        return lstm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.lstm4
     *
     * @param lstm4 the value for recommanddes.lstm4
     *
     * @mbg.generated
     */
    public void setLstm4(String lstm4) {
        this.lstm4 = lstm4 == null ? null : lstm4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.lstm5
     *
     * @return the value of recommanddes.lstm5
     *
     * @mbg.generated
     */
    public String getLstm5() {
        return lstm5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.lstm5
     *
     * @param lstm5 the value for recommanddes.lstm5
     *
     * @mbg.generated
     */
    public void setLstm5(String lstm5) {
        this.lstm5 = lstm5 == null ? null : lstm5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.lstm6
     *
     * @return the value of recommanddes.lstm6
     *
     * @mbg.generated
     */
    public String getLstm6() {
        return lstm6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.lstm6
     *
     * @param lstm6 the value for recommanddes.lstm6
     *
     * @mbg.generated
     */
    public void setLstm6(String lstm6) {
        this.lstm6 = lstm6 == null ? null : lstm6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.lstm7
     *
     * @return the value of recommanddes.lstm7
     *
     * @mbg.generated
     */
    public String getLstm7() {
        return lstm7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.lstm7
     *
     * @param lstm7 the value for recommanddes.lstm7
     *
     * @mbg.generated
     */
    public void setLstm7(String lstm7) {
        this.lstm7 = lstm7 == null ? null : lstm7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.lstm8
     *
     * @return the value of recommanddes.lstm8
     *
     * @mbg.generated
     */
    public String getLstm8() {
        return lstm8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.lstm8
     *
     * @param lstm8 the value for recommanddes.lstm8
     *
     * @mbg.generated
     */
    public void setLstm8(String lstm8) {
        this.lstm8 = lstm8 == null ? null : lstm8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.lstm9
     *
     * @return the value of recommanddes.lstm9
     *
     * @mbg.generated
     */
    public String getLstm9() {
        return lstm9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.lstm9
     *
     * @param lstm9 the value for recommanddes.lstm9
     *
     * @mbg.generated
     */
    public void setLstm9(String lstm9) {
        this.lstm9 = lstm9 == null ? null : lstm9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.lstm10
     *
     * @return the value of recommanddes.lstm10
     *
     * @mbg.generated
     */
    public String getLstm10() {
        return lstm10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.lstm10
     *
     * @param lstm10 the value for recommanddes.lstm10
     *
     * @mbg.generated
     */
    public void setLstm10(String lstm10) {
        this.lstm10 = lstm10 == null ? null : lstm10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.nn1
     *
     * @return the value of recommanddes.nn1
     *
     * @mbg.generated
     */
    public String getNn1() {
        return nn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.nn1
     *
     * @param nn1 the value for recommanddes.nn1
     *
     * @mbg.generated
     */
    public void setNn1(String nn1) {
        this.nn1 = nn1 == null ? null : nn1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.nn2
     *
     * @return the value of recommanddes.nn2
     *
     * @mbg.generated
     */
    public String getNn2() {
        return nn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.nn2
     *
     * @param nn2 the value for recommanddes.nn2
     *
     * @mbg.generated
     */
    public void setNn2(String nn2) {
        this.nn2 = nn2 == null ? null : nn2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.nn3
     *
     * @return the value of recommanddes.nn3
     *
     * @mbg.generated
     */
    public String getNn3() {
        return nn3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.nn3
     *
     * @param nn3 the value for recommanddes.nn3
     *
     * @mbg.generated
     */
    public void setNn3(String nn3) {
        this.nn3 = nn3 == null ? null : nn3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.nn4
     *
     * @return the value of recommanddes.nn4
     *
     * @mbg.generated
     */
    public String getNn4() {
        return nn4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.nn4
     *
     * @param nn4 the value for recommanddes.nn4
     *
     * @mbg.generated
     */
    public void setNn4(String nn4) {
        this.nn4 = nn4 == null ? null : nn4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.nn5
     *
     * @return the value of recommanddes.nn5
     *
     * @mbg.generated
     */
    public String getNn5() {
        return nn5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.nn5
     *
     * @param nn5 the value for recommanddes.nn5
     *
     * @mbg.generated
     */
    public void setNn5(String nn5) {
        this.nn5 = nn5 == null ? null : nn5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.nn6
     *
     * @return the value of recommanddes.nn6
     *
     * @mbg.generated
     */
    public String getNn6() {
        return nn6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.nn6
     *
     * @param nn6 the value for recommanddes.nn6
     *
     * @mbg.generated
     */
    public void setNn6(String nn6) {
        this.nn6 = nn6 == null ? null : nn6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.nn7
     *
     * @return the value of recommanddes.nn7
     *
     * @mbg.generated
     */
    public String getNn7() {
        return nn7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.nn7
     *
     * @param nn7 the value for recommanddes.nn7
     *
     * @mbg.generated
     */
    public void setNn7(String nn7) {
        this.nn7 = nn7 == null ? null : nn7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.nn8
     *
     * @return the value of recommanddes.nn8
     *
     * @mbg.generated
     */
    public String getNn8() {
        return nn8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.nn8
     *
     * @param nn8 the value for recommanddes.nn8
     *
     * @mbg.generated
     */
    public void setNn8(String nn8) {
        this.nn8 = nn8 == null ? null : nn8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.nn9
     *
     * @return the value of recommanddes.nn9
     *
     * @mbg.generated
     */
    public String getNn9() {
        return nn9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.nn9
     *
     * @param nn9 the value for recommanddes.nn9
     *
     * @mbg.generated
     */
    public void setNn9(String nn9) {
        this.nn9 = nn9 == null ? null : nn9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.nn10
     *
     * @return the value of recommanddes.nn10
     *
     * @mbg.generated
     */
    public String getNn10() {
        return nn10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.nn10
     *
     * @param nn10 the value for recommanddes.nn10
     *
     * @mbg.generated
     */
    public void setNn10(String nn10) {
        this.nn10 = nn10 == null ? null : nn10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.cnn1
     *
     * @return the value of recommanddes.cnn1
     *
     * @mbg.generated
     */
    public String getCnn1() {
        return cnn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.cnn1
     *
     * @param cnn1 the value for recommanddes.cnn1
     *
     * @mbg.generated
     */
    public void setCnn1(String cnn1) {
        this.cnn1 = cnn1 == null ? null : cnn1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.cnn2
     *
     * @return the value of recommanddes.cnn2
     *
     * @mbg.generated
     */
    public String getCnn2() {
        return cnn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.cnn2
     *
     * @param cnn2 the value for recommanddes.cnn2
     *
     * @mbg.generated
     */
    public void setCnn2(String cnn2) {
        this.cnn2 = cnn2 == null ? null : cnn2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.cnn3
     *
     * @return the value of recommanddes.cnn3
     *
     * @mbg.generated
     */
    public String getCnn3() {
        return cnn3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.cnn3
     *
     * @param cnn3 the value for recommanddes.cnn3
     *
     * @mbg.generated
     */
    public void setCnn3(String cnn3) {
        this.cnn3 = cnn3 == null ? null : cnn3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.cnn4
     *
     * @return the value of recommanddes.cnn4
     *
     * @mbg.generated
     */
    public String getCnn4() {
        return cnn4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.cnn4
     *
     * @param cnn4 the value for recommanddes.cnn4
     *
     * @mbg.generated
     */
    public void setCnn4(String cnn4) {
        this.cnn4 = cnn4 == null ? null : cnn4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.cnn5
     *
     * @return the value of recommanddes.cnn5
     *
     * @mbg.generated
     */
    public String getCnn5() {
        return cnn5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.cnn5
     *
     * @param cnn5 the value for recommanddes.cnn5
     *
     * @mbg.generated
     */
    public void setCnn5(String cnn5) {
        this.cnn5 = cnn5 == null ? null : cnn5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.cnn6
     *
     * @return the value of recommanddes.cnn6
     *
     * @mbg.generated
     */
    public String getCnn6() {
        return cnn6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.cnn6
     *
     * @param cnn6 the value for recommanddes.cnn6
     *
     * @mbg.generated
     */
    public void setCnn6(String cnn6) {
        this.cnn6 = cnn6 == null ? null : cnn6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.cnn7
     *
     * @return the value of recommanddes.cnn7
     *
     * @mbg.generated
     */
    public String getCnn7() {
        return cnn7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.cnn7
     *
     * @param cnn7 the value for recommanddes.cnn7
     *
     * @mbg.generated
     */
    public void setCnn7(String cnn7) {
        this.cnn7 = cnn7 == null ? null : cnn7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.cnn8
     *
     * @return the value of recommanddes.cnn8
     *
     * @mbg.generated
     */
    public String getCnn8() {
        return cnn8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.cnn8
     *
     * @param cnn8 the value for recommanddes.cnn8
     *
     * @mbg.generated
     */
    public void setCnn8(String cnn8) {
        this.cnn8 = cnn8 == null ? null : cnn8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.cnn9
     *
     * @return the value of recommanddes.cnn9
     *
     * @mbg.generated
     */
    public String getCnn9() {
        return cnn9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.cnn9
     *
     * @param cnn9 the value for recommanddes.cnn9
     *
     * @mbg.generated
     */
    public void setCnn9(String cnn9) {
        this.cnn9 = cnn9 == null ? null : cnn9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.cnn10
     *
     * @return the value of recommanddes.cnn10
     *
     * @mbg.generated
     */
    public String getCnn10() {
        return cnn10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.cnn10
     *
     * @param cnn10 the value for recommanddes.cnn10
     *
     * @mbg.generated
     */
    public void setCnn10(String cnn10) {
        this.cnn10 = cnn10 == null ? null : cnn10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.tfidf1
     *
     * @return the value of recommanddes.tfidf1
     *
     * @mbg.generated
     */
    public String getTfidf1() {
        return tfidf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.tfidf1
     *
     * @param tfidf1 the value for recommanddes.tfidf1
     *
     * @mbg.generated
     */
    public void setTfidf1(String tfidf1) {
        this.tfidf1 = tfidf1 == null ? null : tfidf1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.tfidf2
     *
     * @return the value of recommanddes.tfidf2
     *
     * @mbg.generated
     */
    public String getTfidf2() {
        return tfidf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.tfidf2
     *
     * @param tfidf2 the value for recommanddes.tfidf2
     *
     * @mbg.generated
     */
    public void setTfidf2(String tfidf2) {
        this.tfidf2 = tfidf2 == null ? null : tfidf2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.tfidf3
     *
     * @return the value of recommanddes.tfidf3
     *
     * @mbg.generated
     */
    public String getTfidf3() {
        return tfidf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.tfidf3
     *
     * @param tfidf3 the value for recommanddes.tfidf3
     *
     * @mbg.generated
     */
    public void setTfidf3(String tfidf3) {
        this.tfidf3 = tfidf3 == null ? null : tfidf3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.tfidf4
     *
     * @return the value of recommanddes.tfidf4
     *
     * @mbg.generated
     */
    public String getTfidf4() {
        return tfidf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.tfidf4
     *
     * @param tfidf4 the value for recommanddes.tfidf4
     *
     * @mbg.generated
     */
    public void setTfidf4(String tfidf4) {
        this.tfidf4 = tfidf4 == null ? null : tfidf4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.tfidf5
     *
     * @return the value of recommanddes.tfidf5
     *
     * @mbg.generated
     */
    public String getTfidf5() {
        return tfidf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.tfidf5
     *
     * @param tfidf5 the value for recommanddes.tfidf5
     *
     * @mbg.generated
     */
    public void setTfidf5(String tfidf5) {
        this.tfidf5 = tfidf5 == null ? null : tfidf5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.tfidf6
     *
     * @return the value of recommanddes.tfidf6
     *
     * @mbg.generated
     */
    public String getTfidf6() {
        return tfidf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.tfidf6
     *
     * @param tfidf6 the value for recommanddes.tfidf6
     *
     * @mbg.generated
     */
    public void setTfidf6(String tfidf6) {
        this.tfidf6 = tfidf6 == null ? null : tfidf6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.tfidf7
     *
     * @return the value of recommanddes.tfidf7
     *
     * @mbg.generated
     */
    public String getTfidf7() {
        return tfidf7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.tfidf7
     *
     * @param tfidf7 the value for recommanddes.tfidf7
     *
     * @mbg.generated
     */
    public void setTfidf7(String tfidf7) {
        this.tfidf7 = tfidf7 == null ? null : tfidf7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.tfidf8
     *
     * @return the value of recommanddes.tfidf8
     *
     * @mbg.generated
     */
    public String getTfidf8() {
        return tfidf8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.tfidf8
     *
     * @param tfidf8 the value for recommanddes.tfidf8
     *
     * @mbg.generated
     */
    public void setTfidf8(String tfidf8) {
        this.tfidf8 = tfidf8 == null ? null : tfidf8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.tfidf9
     *
     * @return the value of recommanddes.tfidf9
     *
     * @mbg.generated
     */
    public String getTfidf9() {
        return tfidf9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.tfidf9
     *
     * @param tfidf9 the value for recommanddes.tfidf9
     *
     * @mbg.generated
     */
    public void setTfidf9(String tfidf9) {
        this.tfidf9 = tfidf9 == null ? null : tfidf9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.tfidf10
     *
     * @return the value of recommanddes.tfidf10
     *
     * @mbg.generated
     */
    public String getTfidf10() {
        return tfidf10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.tfidf10
     *
     * @param tfidf10 the value for recommanddes.tfidf10
     *
     * @mbg.generated
     */
    public void setTfidf10(String tfidf10) {
        this.tfidf10 = tfidf10 == null ? null : tfidf10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.doc1
     *
     * @return the value of recommanddes.doc1
     *
     * @mbg.generated
     */
    public String getDoc1() {
        return doc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.doc1
     *
     * @param doc1 the value for recommanddes.doc1
     *
     * @mbg.generated
     */
    public void setDoc1(String doc1) {
        this.doc1 = doc1 == null ? null : doc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.doc2
     *
     * @return the value of recommanddes.doc2
     *
     * @mbg.generated
     */
    public String getDoc2() {
        return doc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.doc2
     *
     * @param doc2 the value for recommanddes.doc2
     *
     * @mbg.generated
     */
    public void setDoc2(String doc2) {
        this.doc2 = doc2 == null ? null : doc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.doc3
     *
     * @return the value of recommanddes.doc3
     *
     * @mbg.generated
     */
    public String getDoc3() {
        return doc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.doc3
     *
     * @param doc3 the value for recommanddes.doc3
     *
     * @mbg.generated
     */
    public void setDoc3(String doc3) {
        this.doc3 = doc3 == null ? null : doc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.doc4
     *
     * @return the value of recommanddes.doc4
     *
     * @mbg.generated
     */
    public String getDoc4() {
        return doc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.doc4
     *
     * @param doc4 the value for recommanddes.doc4
     *
     * @mbg.generated
     */
    public void setDoc4(String doc4) {
        this.doc4 = doc4 == null ? null : doc4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.doc5
     *
     * @return the value of recommanddes.doc5
     *
     * @mbg.generated
     */
    public String getDoc5() {
        return doc5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.doc5
     *
     * @param doc5 the value for recommanddes.doc5
     *
     * @mbg.generated
     */
    public void setDoc5(String doc5) {
        this.doc5 = doc5 == null ? null : doc5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.doc6
     *
     * @return the value of recommanddes.doc6
     *
     * @mbg.generated
     */
    public String getDoc6() {
        return doc6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.doc6
     *
     * @param doc6 the value for recommanddes.doc6
     *
     * @mbg.generated
     */
    public void setDoc6(String doc6) {
        this.doc6 = doc6 == null ? null : doc6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.doc7
     *
     * @return the value of recommanddes.doc7
     *
     * @mbg.generated
     */
    public String getDoc7() {
        return doc7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.doc7
     *
     * @param doc7 the value for recommanddes.doc7
     *
     * @mbg.generated
     */
    public void setDoc7(String doc7) {
        this.doc7 = doc7 == null ? null : doc7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.doc8
     *
     * @return the value of recommanddes.doc8
     *
     * @mbg.generated
     */
    public String getDoc8() {
        return doc8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.doc8
     *
     * @param doc8 the value for recommanddes.doc8
     *
     * @mbg.generated
     */
    public void setDoc8(String doc8) {
        this.doc8 = doc8 == null ? null : doc8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.doc9
     *
     * @return the value of recommanddes.doc9
     *
     * @mbg.generated
     */
    public String getDoc9() {
        return doc9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.doc9
     *
     * @param doc9 the value for recommanddes.doc9
     *
     * @mbg.generated
     */
    public void setDoc9(String doc9) {
        this.doc9 = doc9 == null ? null : doc9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.doc10
     *
     * @return the value of recommanddes.doc10
     *
     * @mbg.generated
     */
    public String getDoc10() {
        return doc10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.doc10
     *
     * @param doc10 the value for recommanddes.doc10
     *
     * @mbg.generated
     */
    public void setDoc10(String doc10) {
        this.doc10 = doc10 == null ? null : doc10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.index1
     *
     * @return the value of recommanddes.index1
     *
     * @mbg.generated
     */
    public String getIndex1() {
        return index1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.index1
     *
     * @param index1 the value for recommanddes.index1
     *
     * @mbg.generated
     */
    public void setIndex1(String index1) {
        this.index1 = index1 == null ? null : index1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.index2
     *
     * @return the value of recommanddes.index2
     *
     * @mbg.generated
     */
    public String getIndex2() {
        return index2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.index2
     *
     * @param index2 the value for recommanddes.index2
     *
     * @mbg.generated
     */
    public void setIndex2(String index2) {
        this.index2 = index2 == null ? null : index2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.index3
     *
     * @return the value of recommanddes.index3
     *
     * @mbg.generated
     */
    public String getIndex3() {
        return index3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.index3
     *
     * @param index3 the value for recommanddes.index3
     *
     * @mbg.generated
     */
    public void setIndex3(String index3) {
        this.index3 = index3 == null ? null : index3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.index4
     *
     * @return the value of recommanddes.index4
     *
     * @mbg.generated
     */
    public String getIndex4() {
        return index4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.index4
     *
     * @param index4 the value for recommanddes.index4
     *
     * @mbg.generated
     */
    public void setIndex4(String index4) {
        this.index4 = index4 == null ? null : index4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.index5
     *
     * @return the value of recommanddes.index5
     *
     * @mbg.generated
     */
    public String getIndex5() {
        return index5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.index5
     *
     * @param index5 the value for recommanddes.index5
     *
     * @mbg.generated
     */
    public void setIndex5(String index5) {
        this.index5 = index5 == null ? null : index5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.index6
     *
     * @return the value of recommanddes.index6
     *
     * @mbg.generated
     */
    public String getIndex6() {
        return index6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.index6
     *
     * @param index6 the value for recommanddes.index6
     *
     * @mbg.generated
     */
    public void setIndex6(String index6) {
        this.index6 = index6 == null ? null : index6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.index7
     *
     * @return the value of recommanddes.index7
     *
     * @mbg.generated
     */
    public String getIndex7() {
        return index7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.index7
     *
     * @param index7 the value for recommanddes.index7
     *
     * @mbg.generated
     */
    public void setIndex7(String index7) {
        this.index7 = index7 == null ? null : index7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.index8
     *
     * @return the value of recommanddes.index8
     *
     * @mbg.generated
     */
    public String getIndex8() {
        return index8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.index8
     *
     * @param index8 the value for recommanddes.index8
     *
     * @mbg.generated
     */
    public void setIndex8(String index8) {
        this.index8 = index8 == null ? null : index8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.index9
     *
     * @return the value of recommanddes.index9
     *
     * @mbg.generated
     */
    public String getIndex9() {
        return index9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.index9
     *
     * @param index9 the value for recommanddes.index9
     *
     * @mbg.generated
     */
    public void setIndex9(String index9) {
        this.index9 = index9 == null ? null : index9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommanddes.index10
     *
     * @return the value of recommanddes.index10
     *
     * @mbg.generated
     */
    public String getIndex10() {
        return index10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommanddes.index10
     *
     * @param index10 the value for recommanddes.index10
     *
     * @mbg.generated
     */
    public void setIndex10(String index10) {
        this.index10 = index10 == null ? null : index10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommanddes
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inputname=").append(inputname);
        sb.append(", inputdes=").append(inputdes);
        sb.append(", lstm1=").append(lstm1);
        sb.append(", lstm2=").append(lstm2);
        sb.append(", lstm3=").append(lstm3);
        sb.append(", lstm4=").append(lstm4);
        sb.append(", lstm5=").append(lstm5);
        sb.append(", lstm6=").append(lstm6);
        sb.append(", lstm7=").append(lstm7);
        sb.append(", lstm8=").append(lstm8);
        sb.append(", lstm9=").append(lstm9);
        sb.append(", lstm10=").append(lstm10);
        sb.append(", nn1=").append(nn1);
        sb.append(", nn2=").append(nn2);
        sb.append(", nn3=").append(nn3);
        sb.append(", nn4=").append(nn4);
        sb.append(", nn5=").append(nn5);
        sb.append(", nn6=").append(nn6);
        sb.append(", nn7=").append(nn7);
        sb.append(", nn8=").append(nn8);
        sb.append(", nn9=").append(nn9);
        sb.append(", nn10=").append(nn10);
        sb.append(", cnn1=").append(cnn1);
        sb.append(", cnn2=").append(cnn2);
        sb.append(", cnn3=").append(cnn3);
        sb.append(", cnn4=").append(cnn4);
        sb.append(", cnn5=").append(cnn5);
        sb.append(", cnn6=").append(cnn6);
        sb.append(", cnn7=").append(cnn7);
        sb.append(", cnn8=").append(cnn8);
        sb.append(", cnn9=").append(cnn9);
        sb.append(", cnn10=").append(cnn10);
        sb.append(", tfidf1=").append(tfidf1);
        sb.append(", tfidf2=").append(tfidf2);
        sb.append(", tfidf3=").append(tfidf3);
        sb.append(", tfidf4=").append(tfidf4);
        sb.append(", tfidf5=").append(tfidf5);
        sb.append(", tfidf6=").append(tfidf6);
        sb.append(", tfidf7=").append(tfidf7);
        sb.append(", tfidf8=").append(tfidf8);
        sb.append(", tfidf9=").append(tfidf9);
        sb.append(", tfidf10=").append(tfidf10);
        sb.append(", doc1=").append(doc1);
        sb.append(", doc2=").append(doc2);
        sb.append(", doc3=").append(doc3);
        sb.append(", doc4=").append(doc4);
        sb.append(", doc5=").append(doc5);
        sb.append(", doc6=").append(doc6);
        sb.append(", doc7=").append(doc7);
        sb.append(", doc8=").append(doc8);
        sb.append(", doc9=").append(doc9);
        sb.append(", doc10=").append(doc10);
        sb.append(", index1=").append(index1);
        sb.append(", index2=").append(index2);
        sb.append(", index3=").append(index3);
        sb.append(", index4=").append(index4);
        sb.append(", index5=").append(index5);
        sb.append(", index6=").append(index6);
        sb.append(", index7=").append(index7);
        sb.append(", index8=").append(index8);
        sb.append(", index9=").append(index9);
        sb.append(", index10=").append(index10);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public List des(){
        List list = new ArrayList();
        list.add(lstm1);
        list.add(lstm2);
        list.add(lstm3);
        list.add(lstm4);
        list.add(lstm5);
        list.add(lstm6);
        list.add(lstm7);
        list.add(lstm8);
        list.add(lstm9);
        list.add(lstm10);
        list.add(nn1);
        list.add(nn2);
        list.add(nn3);
        list.add(nn4);
        list.add(nn4);
        list.add(nn5);
        list.add(nn6);
        list.add(nn7);
        list.add(nn8);
        list.add(nn9);
        list.add(nn9);
        list.add(nn10);
        list.add(cnn1);
        list.add(cnn2);
        list.add(cnn3);
        list.add(cnn4);
        list.add(cnn5);
        list.add(cnn6);
        list.add(cnn7);
        list.add(cnn8);
        list.add(cnn9);
        list.add(cnn10);
        list.add(tfidf1);
        list.add(tfidf2);
        list.add(tfidf3);
        list.add(tfidf4);
        list.add(tfidf5);
        list.add(tfidf6);
        list.add(tfidf7);
        list.add(tfidf8);
        list.add(tfidf9);
        list.add(tfidf10);
        list.add(doc1);
        list.add(doc2);
        list.add(doc3);
        list.add(doc4);
        list.add(doc5);
        list.add(doc6);
        list.add(doc7);
        list.add(doc8);
        list.add(doc9);
        list.add(doc10);
        list.add(index1);
        list.add(index2);
        list.add(index3);
        list.add(index4);
        list.add(index5);
        list.add(index6);
        list.add(index7);
        list.add(index8);
        list.add(index9);
        list.add(index10);
        return list;
    }
}