package com.wx.assigntask.entity;

import java.io.Serializable;

public class Release implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.releaseId
     *
     * @mbg.generated
     */
    private Integer releaseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.inputName
     *
     * @mbg.generated
     */
    private String inputname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.inputDes
     *
     * @mbg.generated
     */
    private String inputdes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.algs
     *
     * @mbg.generated
     */
    private String algs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.ifComplete
     *
     * @mbg.generated
     */
    private String ifcomplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.winAlgname
     *
     * @mbg.generated
     */
    private String winalgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table release
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.releaseId
     *
     * @return the value of release.releaseId
     *
     * @mbg.generated
     */
    public Integer getReleaseid() {
        return releaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.releaseId
     *
     * @param releaseid the value for release.releaseId
     *
     * @mbg.generated
     */
    public void setReleaseid(Integer releaseid) {
        this.releaseid = releaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.inputName
     *
     * @return the value of release.inputName
     *
     * @mbg.generated
     */
    public String getInputname() {
        return inputname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.inputName
     *
     * @param inputname the value for release.inputName
     *
     * @mbg.generated
     */
    public void setInputname(String inputname) {
        this.inputname = inputname == null ? null : inputname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.inputDes
     *
     * @return the value of release.inputDes
     *
     * @mbg.generated
     */
    public String getInputdes() {
        return inputdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.inputDes
     *
     * @param inputdes the value for release.inputDes
     *
     * @mbg.generated
     */
    public void setInputdes(String inputdes) {
        this.inputdes = inputdes == null ? null : inputdes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.algs
     *
     * @return the value of release.algs
     *
     * @mbg.generated
     */
    public String getAlgs() {
        return algs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.algs
     *
     * @param algs the value for release.algs
     *
     * @mbg.generated
     */
    public void setAlgs(String algs) {
        this.algs = algs == null ? null : algs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.ifComplete
     *
     * @return the value of release.ifComplete
     *
     * @mbg.generated
     */
    public String getIfcomplete() {
        return ifcomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.ifComplete
     *
     * @param ifcomplete the value for release.ifComplete
     *
     * @mbg.generated
     */
    public void setIfcomplete(String ifcomplete) {
        this.ifcomplete = ifcomplete == null ? null : ifcomplete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.winAlgname
     *
     * @return the value of release.winAlgname
     *
     * @mbg.generated
     */
    public String getWinalgname() {
        return winalgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.winAlgname
     *
     * @param winalgname the value for release.winAlgname
     *
     * @mbg.generated
     */
    public void setWinalgname(String winalgname) {
        this.winalgname = winalgname == null ? null : winalgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.result
     *
     * @return the value of release.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.result
     *
     * @param result the value for release.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", releaseid=").append(releaseid);
        sb.append(", inputname=").append(inputname);
        sb.append(", inputdes=").append(inputdes);
        sb.append(", algs=").append(algs);
        sb.append(", ifcomplete=").append(ifcomplete);
        sb.append(", winalgname=").append(winalgname);
        sb.append(", result=").append(result);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}