package com.wx.assigntask.entity;

import java.io.Serializable;

public class Subdata implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subdata.subdataId
     *
     * @mbg.generated
     */
    private Integer subdataid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subdata.subtaskId
     *
     * @mbg.generated
     */
    private Integer subtaskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subdata.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subdata.randomNum
     *
     * @mbg.generated
     */
    private Integer randomnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subdata.score1
     *
     * @mbg.generated
     */
    private Integer score1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subdata.score2
     *
     * @mbg.generated
     */
    private Integer score2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subdata
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subdata.subdataId
     *
     * @return the value of subdata.subdataId
     *
     * @mbg.generated
     */
    public Integer getSubdataid() {
        return subdataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subdata.subdataId
     *
     * @param subdataid the value for subdata.subdataId
     *
     * @mbg.generated
     */
    public void setSubdataid(Integer subdataid) {
        this.subdataid = subdataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subdata.subtaskId
     *
     * @return the value of subdata.subtaskId
     *
     * @mbg.generated
     */
    public Integer getSubtaskid() {
        return subtaskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subdata.subtaskId
     *
     * @param subtaskid the value for subdata.subtaskId
     *
     * @mbg.generated
     */
    public void setSubtaskid(Integer subtaskid) {
        this.subtaskid = subtaskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subdata.userId
     *
     * @return the value of subdata.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subdata.userId
     *
     * @param userid the value for subdata.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subdata.randomNum
     *
     * @return the value of subdata.randomNum
     *
     * @mbg.generated
     */
    public Integer getRandomnum() {
        return randomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subdata.randomNum
     *
     * @param randomnum the value for subdata.randomNum
     *
     * @mbg.generated
     */
    public void setRandomnum(Integer randomnum) {
        this.randomnum = randomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subdata.score1
     *
     * @return the value of subdata.score1
     *
     * @mbg.generated
     */
    public Integer getScore1() {
        return score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subdata.score1
     *
     * @param score1 the value for subdata.score1
     *
     * @mbg.generated
     */
    public void setScore1(Integer score1) {
        this.score1 = score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subdata.score2
     *
     * @return the value of subdata.score2
     *
     * @mbg.generated
     */
    public Integer getScore2() {
        return score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subdata.score2
     *
     * @param score2 the value for subdata.score2
     *
     * @mbg.generated
     */
    public void setScore2(Integer score2) {
        this.score2 = score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subdata
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", subdataid=").append(subdataid);
        sb.append(", subtaskid=").append(subtaskid);
        sb.append(", userid=").append(userid);
        sb.append(", randomnum=").append(randomnum);
        sb.append(", score1=").append(score1);
        sb.append(", score2=").append(score2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}