package com.wx.assigntask.entity;

import java.io.Serializable;

public class Subtask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.subtaskId
     *
     * @mbg.generated
     */
    private Integer subtaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.dividedId
     *
     * @mbg.generated
     */
    private Integer dividedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.inputName
     *
     * @mbg.generated
     */
    private String inputName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.itemName1
     *
     * @mbg.generated
     */
    private String itemName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.itemName2
     *
     * @mbg.generated
     */
    private String itemName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.score1
     *
     * @mbg.generated
     */
    private Float score1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.score2
     *
     * @mbg.generated
     */
    private Float score2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.randomNum
     *
     * @mbg.generated
     */
    private Integer randomNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.frequency
     *
     * @mbg.generated
     */
    private Integer frequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.inputDes
     *
     * @mbg.generated
     */
    private String inputDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.itemDes1
     *
     * @mbg.generated
     */
    private String itemDes1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtask.itemDes2
     *
     * @mbg.generated
     */
    private String itemDes2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subtask
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.subtaskId
     *
     * @return the value of subtask.subtaskId
     *
     * @mbg.generated
     */
    public Integer getSubtaskId() {
        return subtaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.subtaskId
     *
     * @param subtaskId the value for subtask.subtaskId
     *
     * @mbg.generated
     */
    public void setSubtaskId(Integer subtaskId) {
        this.subtaskId = subtaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.dividedId
     *
     * @return the value of subtask.dividedId
     *
     * @mbg.generated
     */
    public Integer getDividedId() {
        return dividedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.dividedId
     *
     * @param dividedId the value for subtask.dividedId
     *
     * @mbg.generated
     */
    public void setDividedId(Integer dividedId) {
        this.dividedId = dividedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.inputName
     *
     * @return the value of subtask.inputName
     *
     * @mbg.generated
     */
    public String getInputName() {
        return inputName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.inputName
     *
     * @param inputName the value for subtask.inputName
     *
     * @mbg.generated
     */
    public void setInputName(String inputName) {
        this.inputName = inputName == null ? null : inputName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.itemName1
     *
     * @return the value of subtask.itemName1
     *
     * @mbg.generated
     */
    public String getItemName1() {
        return itemName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.itemName1
     *
     * @param itemName1 the value for subtask.itemName1
     *
     * @mbg.generated
     */
    public void setItemName1(String itemName1) {
        this.itemName1 = itemName1 == null ? null : itemName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.itemName2
     *
     * @return the value of subtask.itemName2
     *
     * @mbg.generated
     */
    public String getItemName2() {
        return itemName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.itemName2
     *
     * @param itemName2 the value for subtask.itemName2
     *
     * @mbg.generated
     */
    public void setItemName2(String itemName2) {
        this.itemName2 = itemName2 == null ? null : itemName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.score1
     *
     * @return the value of subtask.score1
     *
     * @mbg.generated
     */
    public Float getScore1() {
        return score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.score1
     *
     * @param score1 the value for subtask.score1
     *
     * @mbg.generated
     */
    public void setScore1(Float score1) {
        this.score1 = score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.score2
     *
     * @return the value of subtask.score2
     *
     * @mbg.generated
     */
    public Float getScore2() {
        return score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.score2
     *
     * @param score2 the value for subtask.score2
     *
     * @mbg.generated
     */
    public void setScore2(Float score2) {
        this.score2 = score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.randomNum
     *
     * @return the value of subtask.randomNum
     *
     * @mbg.generated
     */
    public Integer getRandomNum() {
        return randomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.randomNum
     *
     * @param randomNum the value for subtask.randomNum
     *
     * @mbg.generated
     */
    public void setRandomNum(Integer randomNum) {
        this.randomNum = randomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.frequency
     *
     * @return the value of subtask.frequency
     *
     * @mbg.generated
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.frequency
     *
     * @param frequency the value for subtask.frequency
     *
     * @mbg.generated
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.inputDes
     *
     * @return the value of subtask.inputDes
     *
     * @mbg.generated
     */
    public String getInputDes() {
        return inputDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.inputDes
     *
     * @param inputDes the value for subtask.inputDes
     *
     * @mbg.generated
     */
    public void setInputDes(String inputDes) {
        this.inputDes = inputDes == null ? null : inputDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.itemDes1
     *
     * @return the value of subtask.itemDes1
     *
     * @mbg.generated
     */
    public String getItemDes1() {
        return itemDes1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.itemDes1
     *
     * @param itemDes1 the value for subtask.itemDes1
     *
     * @mbg.generated
     */
    public void setItemDes1(String itemDes1) {
        this.itemDes1 = itemDes1 == null ? null : itemDes1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtask.itemDes2
     *
     * @return the value of subtask.itemDes2
     *
     * @mbg.generated
     */
    public String getItemDes2() {
        return itemDes2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtask.itemDes2
     *
     * @param itemDes2 the value for subtask.itemDes2
     *
     * @mbg.generated
     */
    public void setItemDes2(String itemDes2) {
        this.itemDes2 = itemDes2 == null ? null : itemDes2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", subtaskId=").append(subtaskId);
        sb.append(", dividedId=").append(dividedId);
        sb.append(", inputName=").append(inputName);
        sb.append(", itemName1=").append(itemName1);
        sb.append(", itemName2=").append(itemName2);
        sb.append(", score1=").append(score1);
        sb.append(", score2=").append(score2);
        sb.append(", randomNum=").append(randomNum);
        sb.append(", frequency=").append(frequency);
        sb.append(", inputDes=").append(inputDes);
        sb.append(", itemDes1=").append(itemDes1);
        sb.append(", itemDes2=").append(itemDes2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}