package com.wx.assigntask.entity;

import java.io.Serializable;

public class Userreceive implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertask.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertask.taskId
     *
     * @mbg.generated
     */
    private Integer subtaskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertask.score1
     *
     * @mbg.generated
     */
    private String score1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertask.score2
     *
     * @mbg.generated
     */
    private String score2;

    private int dividedid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usertask
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertask.userId
     *
     * @return the value of usertask.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertask.userId
     *
     * @param userid the value for usertask.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertask.taskId
     *
     * @return the value of usertask.taskId
     *
     * @mbg.generated
     */
    public Integer getTaskid() {
        return subtaskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertask.taskId
     *
     * @param subtaskid the value for usertask.taskId
     *
     * @mbg.generated
     */
    public void setTaskid(Integer subtaskid) {
        this.subtaskid = subtaskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertask.score1
     *
     * @return the value of usertask.score1
     *
     * @mbg.generated
     */
    public String getScore1() {
        return score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertask.score1
     *
     * @param score1 the value for usertask.score1
     *
     * @mbg.generated
     */
    public void setScore1(String score1) {
        this.score1 = score1 == null ? null : score1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertask.score2
     *
     * @return the value of usertask.score2
     *
     * @mbg.generated
     */
    public String getScore2() {
        return score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertask.score2
     *
     * @param score2 the value for usertask.score2
     *
     * @mbg.generated
     */
    public void setScore2(String score2) {
        this.score2 = score2 == null ? null : score2.trim();
    }

    public int getDividedid() {
        return dividedid;
    }

    public void setDividedid(int dividedid) {
        this.dividedid = dividedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", taskid=").append(subtaskid);
        sb.append(", score1=").append(score1);
        sb.append(", score2=").append(score2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}