/*
Navicat MySQL Data Transfer

Source Server         : similarity
Source Server Version : 80011
Source Host           : localhost:3306
Source Database       : similarity

Target Server Type    : MYSQL
Target Server Version : 80011
File Encoding         : 65001

Date: 2018-12-10 16:00:53
*/

use assigntask;
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for recommandname
-- ----------------------------
DROP TABLE IF EXISTS `recommandname`;
CREATE TABLE `recommandname` (
  `inputName` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `algName` text,
  `itemName` text

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of recommandname
-- ----------------------------
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'lstm','PrestaShop e-Commerce Solution');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'lstm','CultBooking Hotel Booking System');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'lstm','justPDF');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'lstm','Grocery List');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'lstm','Lifeograph');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'lstm','Custom: POS, Accounts, Stock Management');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'lstm','Foswiki');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'lstm','EDesk');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'lstm','evimsync');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'lstm','doc2pdf');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'nn','CloneScripts');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'nn','MJP Lab');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'nn','Collaborative Classification');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'nn','F4L');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'nn','An NS2 TCP Evaluation Tool');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'nn','yieldbuddy');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'nn','Remote Sensing Downloader');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'nn','Folding@Home Grapher');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'nn','Soru Cevap Scripti');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'nn','Dequiem');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'cnn','Vulture Network Engine');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'cnn','UniversalIDE');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'cnn','Isolation Forest');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'cnn','uGet - Download Manager');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'cnn','EJBBuilder');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'cnn','Liferay Security Patches');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'cnn','GDBMS gvSIG plugins');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'cnn','LinSSID');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'cnn','openPOWERLINK');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'cnn','Pumilio');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'tfidf','bluemapia');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'tfidf','Open GPS Tracking System');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'tfidf','pPGallery');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'tfidf','collectw');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'tfidf','Chemical Structures');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'tfidf','Humboldt WMS Viewer');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'tfidf','ZoomifyImage');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'tfidf','Silex, live web creation');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project','tfidf','SEO Panel - A control panel for SEO');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'doc','NeDi');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'doc','Smart Cache Loader');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'doc','ModSecurity');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project','doc','benchlab');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'doc','IPplan IP address management system');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'doc','C# SOAP Client');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'doc','blocksnet');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'doc','Avaya CMS Real Time Interfaces');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'doc','Screen Squid');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'doc','Screen Squid');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'index','\"Virtual Town\" project');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'index','bluemapia');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'index','Open GPS Tracking System');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'index','XASTIR');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'index','QLandkarte GT');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'index','Viking GPS data editor and analyzer');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'index','Terra Incognita');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'index','The TileProxy Project');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'index','Mobile Atlas Creator');
INSERT INTO `recommandname` VALUES ('\"Virtual Town\" project', 'index','CacheMagnet geocaching software');

INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', 'lstm','ART-DECOR');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"',  'lstm','USARSim');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"',    'lstm','MRmap');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', 'lstm','Dr.Oste');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"',  'lstm','BRIC');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"',  'lstm','di-base read Fast Alignment Search Tool');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', 'lstm','42');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"',  'lstm','MASTIFF');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"',   'lstm','Master Thesis: cointegratedVAR');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'lstm','CEDAR Logic Simulator');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'nn','T-SQL developer');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'nn','Violet UML Editor Plugin for Eclipse');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'nn','Flamebird MX BennuGD IDE');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'nn','UbxBasic');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'nn','wxCode - wxWidgets components');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'nn','EiffelStudio');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'nn','Delphi-Java Bridge');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'nn','Notus');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'nn','DaVinci Concurrente');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'nn','plantuml-dependency');

INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'cnn','SmartFrog');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'cnn','Visual Studio Project Converter');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'cnn','JsonRpc-Cpp');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'cnn','SimplyVBUnit');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'cnn','JC O/R Framework & AtomsFramework');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'cnn','Andromeda Web Editor');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'cnn','Advanced DataGridView');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'cnn','Artistic Style Plugin');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'cnn','BibTeXML');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'cnn','Rovio');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'tfidf','Kylix Libs Packaging');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'tfidf','Supernova programming language');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'tfidf','Z-Bar: Managed .NET for Barcode Printers');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'tfidf','EMP Compiler');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'tfidf','Idea Tester');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'tfidf','sljit');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'tfidf','OpenG Toolkit');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'tfidf','Emulation Framework');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'tfidf','checkstyle');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'tfidf','UMU-XACML-Editor');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'doc','Win32++');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'doc','GTranslater');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'doc','Atom');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'doc','MinGWEditLine');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'doc','FBIde');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'doc','OpenGL[tm] for Java[tm]');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'doc','Extreme Ext JS Theme Builder');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'doc','BitVisor');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'doc','Fuzzy Logic Library for Microsoft .Net');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'doc','base64 file encoder/decoder');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'index','\"Windows Free Pascal IDE\"');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'index','Next Generation Programming');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'index','Programming Without Coding Technology');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'index','Critical Nodes');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'index','Pascal XE');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'index','Smart POS System');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'index','CodeSnip');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'index','fpGUI Toolkit');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'index','Violet UML Editor');
INSERT INTO `recommandname` VALUES ('\"Windows Free Pascal IDE\"', '\"Windows Free Pascal IDE\" is Copyright (c) 2014 dr Jaroslaw Szymanda Windows Free Pascal is a free source code editor for programmers of console applications. Designed primarily for students who begin to learn programming. They can quickly write and compile software using open source Pascal compiler developed by \"(c) Free Pascal Team\" (see http://www.freepascal.org). \"Windows Free Pascal IDE\" program is free software and can be redistributed without any restriction.', 'index','Lazarus Code and Component Repository');
