package com.wx.assigntask.dao;

import com.wx.assigntask.entity.Algresult;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface AlgresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algresult
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algresult
     *
     * @mbg.generated
     */
    int insert(Algresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algresult
     *
     * @mbg.generated
     */
    Algresult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algresult
     *
     * @mbg.generated
     */
    List<Algresult> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algresult
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Algresult record);
    void updateScore(Algresult algresult);
    void updateWinAlg(Algresult algresult);
    void updateIffinal(Algresult algresult);

    void insertRecord(Algresult algresult);

    List<Algresult> selectNullWinAlgs();
    List<String> selectNoFinalAlg(int releaseid);
    List<Integer> selectNoFinalIds(int releaseid);
}