package com.wx.assigntask.dao;

import com.wx.assigntask.entity.Inputs;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface InputsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputs
     *
     * @mbg.generated
     */
    int insert(Inputs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputs
     *
     * @mbg.generated
     */
    List<Inputs> selectAll();

    /**
     * 查询该检索表所有内容
     * @param tablesname
     * @return
     */
    List<Inputs> selectAllInput(String tablesname);

}