package com.wx.assigntask.dao;

import com.wx.assigntask.entity.Myreceive;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface MyreceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myreceive
     *
     * @mbg.generated
     */
    int insert(Myreceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myreceive
     *
     * @mbg.generated
     */
    List<Myreceive> selectAll();

    List<Myreceive> selectByUser(int userid);
}