package com.wx.assigntask.dao;

import com.wx.assigntask.entity.OriginalData;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface OriginalDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original_data
     *
     * @mbg.generated
     */
    int insert(OriginalData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original_data
     *
     * @mbg.generated
     */
    OriginalData selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original_data
     *
     * @mbg.generated
     */
    List<OriginalData> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OriginalData record);

    OriginalData selectAllItemDes(int id);
    OriginalData selectAllItemsNames(int id);
}