package com.wx.assigntask.dao;

import com.wx.assigntask.entity.Recommanddes;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface RecommanddesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommanddes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String inputname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommanddes
     *
     * @mbg.generated
     */
    int insert(Recommanddes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommanddes
     *
     * @mbg.generated
     */
    Recommanddes selectByPrimaryKey(String inputname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommanddes
     *
     * @mbg.generated
     */
    List<Recommanddes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommanddes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Recommanddes record);
}