package com.wx.assigntask.dao;

import com.wx.assigntask.entity.Recommand;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface RecommandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommand
     *
     * @mbg.generated
     */
    int insert(Recommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommand
     *
     * @mbg.generated
     */
    List<Recommand> selectAllLstm();
    Recommand selectAllLstmItemsNames(int id);
    Recommand selectAllLstmItemDes(int id);

    List<Recommand> selectAllNn();
    Recommand selectAllNnItemsNames(int id);
    Recommand selectAllNnItemDes(int id);

    List<Recommand> selectAllCnn();
    Recommand selectAllCnnItemsNames(int id);
    Recommand selectAllCnnItemDes(int id);

    List<Recommand> selectAllTfidf();
    Recommand selectAllTfiItemsNames(int id);
    Recommand selectAllTfiItemDes(int id);

    List<Recommand> selectAllDoc();
    Recommand selectAllDocItemsNames(int id);
    Recommand selectAllDocItemDes(int id);

    List<Recommand> selectAllIndex();
    Recommand selectAllIndexItemsNames(int id);
    Recommand selectAllIndexItemDes(int id);
}