package com.wx.assigntask.dao;

import com.wx.assigntask.entity.Recommandname;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface RecommandnameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommandname
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommandname
     *
     * @mbg.generated
     */
    int insert(Recommandname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommandname
     *
     * @mbg.generated
     */
    Recommandname selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommandname
     *
     * @mbg.generated
     */
    List<Recommandname> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommandname
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Recommandname record);
}