package com.wx.assigntask.dao;

import com.wx.assigntask.entity.Release;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface ReleaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer releaseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated
     */
    int insert(Release record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated
     */
    Release selectByPrimaryKey(Integer releaseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated
     */
    List<Release> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Release record);
    /**
     * 插入release
     */

    int insertRelease(Release release);

    /**
     * 查找ifDivided
     */
    String findDivided(int releaseid);

    /**
     * 根据releaseid查找
     * @param releaseid
     * @return
     */
    Release findReleaseById(int releaseid);

    /**
     * 根据userid查找
     * @param userid
     * @return
     */
    List<Release> findByUserid(int userid);

    List<String> selectPlans();

    List<Integer> selectNullResult();

    int updateIfDivided(int releaseid,String ifDivided);

}