package com.wx.assigntask.dao;

import com.wx.assigntask.entity.Releasetables;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface ReleasetablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasetables
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasetables
     *
     * @mbg.generated
     */
    int insert(Releasetables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasetables
     *
     * @mbg.generated
     */
    Releasetables selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasetables
     *
     * @mbg.generated
     */
    List<Releasetables> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table releasetables
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Releasetables record);

//    /**
//     * 根据releaseID、algname查找推荐结果表名
//     * @param releasetables
//     * @return
//     */
//    Releasetables findByIdAlg(Releasetables releasetables);

    /**
     * 根据releaseID、algname查找推荐结果表名
     * @param releaseid
     * @param algname
     * @return
     */
    String findRecoTab(int releaseid,String algname);

    String findInputTab(int releaseid,String algname);


}