package com.wx.assigntask.dao;

import com.wx.assigntask.entity.Subtask;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface SubtaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer subtaskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask
     *
     * @mbg.generated
     */
    int insert(Subtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask
     *
     * @mbg.generated
     */
    Subtask selectByPrimaryKey(Integer subtaskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask
     *
     * @mbg.generated
     */
    List<Subtask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtask
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Subtask record);

    /**
     * 插入subtask
     */
    int insertSubTask(Subtask subtask);

    int updateRandom(Subtask subtask);
}