package com.wx.assigntask.dao;

import com.wx.assigntask.entity.Usertask;
import java.util.List;

public interface UsertaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbg.generated
     */
    int insert(Usertask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertask
     *
     * @mbg.generated
     */
    List<Usertask> selectAll();
}